FT_DPCM_PTR=$c000
	.export _player_music_data
;this file for FamiTone2 library generated by text2data tool
_player_music_data:
	.byte 1
	.word @instruments
	.word @samples-3
	.word @song0ch0,@song0ch1,@song0ch2,@song0ch3,@song0ch4,307,256

@instruments:
	.byte $70 ;instrument $02
	.word @env1,@env3,@env0
	.byte $00
	.byte $b0 ;instrument $03
	.word @env2,@env0,@env0
	.byte $00

@samples:
@env0:
	.byte $c0,$00,$00
@env1:
	.byte $cc,$c9,$c8,$c5,$c4,$c2,$c3,$02,$c2,$03,$c2,$00,$0a
@env2:
	.byte $c8,$c6,$c4,$c3,$c2,$c1,$c2,$c3,$c2,$c1,$c0,$00,$0a
@env3:
	.byte $c0,$c1,$c0,$00,$02


@song0ch0:
	.byte $fb,$01
@song0ch0loop:
@ref0:
	.byte $f9,$f9,$ad
	.byte $fd
	.word @song0ch0loop

@song0ch1:
@song0ch1loop:
@ref1:
	.byte $f9,$f9,$ad
	.byte $fd
	.word @song0ch1loop

@song0ch2:
@song0ch2loop:
@ref2:
	.byte $80,$32,$8d,$00,$91,$34,$8d,$00,$91,$36,$8d,$00,$91,$38,$8d,$00
	.byte $91,$3a,$8d,$00,$91,$28,$8d,$00,$91,$2e,$8d,$00,$91,$30,$8d,$00
	.byte $93
	.byte $fd
	.word @song0ch2loop

@song0ch3:
@song0ch3loop:
@ref3:
	.byte $82,$18,$a1,$18,$89,$1e,$89,$18,$89,$18,$a1,$18,$89,$1e,$89,$18
	.byte $89,$18,$a1,$18,$89,$1e,$89,$18,$89,$18,$a1,$18,$89,$1e,$89,$18
	.byte $8b
	.byte $fd
	.word @song0ch3loop

@song0ch4:
@song0ch4loop:
@ref4:
	.byte $f9,$f9,$ad
	.byte $fd
	.word @song0ch4loop