FT_DPCM_PTR=$c000
	.export _player_music_data
;this file for FamiTone2 library generated by text2data tool
_player_music_data:
	.byte 1
	.word @instruments
	.word @samples-3
	.word @song0ch0,@song0ch1,@song0ch2,@song0ch3,@song0ch4,307,256

@instruments:
	.byte $b0 ;instrument $00
	.word @env1,@env0,@env0
	.byte $00
	.byte $30 ;instrument $01
	.word @env2,@env0,@env0
	.byte $00
	.byte $70 ;instrument $02
	.word @env3,@env5,@env0
	.byte $00
	.byte $30 ;instrument $03
	.word @env4,@env0,@env0
	.byte $00

@samples:
@env0:
	.byte $c0,$00,$00
@env1:
	.byte $c8,$c9,$ca,$ca,$cb,$02,$c9,$c9,$c8,$02,$c7,$0f,$c6,$0d,$c5,$09
	.byte $c4,$05,$c4,$00,$12
@env2:
	.byte $ce,$02,$cd,$cd,$cc,$cc,$cb,$ca,$c9,$c8,$c8,$c7,$c6,$c5,$c5,$c4
	.byte $00,$0f
@env3:
	.byte $cc,$c9,$c8,$c5,$c4,$c2,$c3,$02,$c2,$03,$c2,$00,$0a
@env4:
	.byte $cc,$ca,$c8,$c6,$c4,$c2,$c0,$00,$06
@env5:
	.byte $c0,$c1,$c0,$00,$02


@song0ch0:
	.byte $fb,$01
@song0ch0loop:
@ref0:
	.byte $00,$ad,$82,$22,$85,$80,$52,$85,$00,$8d,$82,$30,$8d,$00,$83
@ref1:
	.byte $89,$40,$85,$80,$58,$85,$00,$8d,$82,$30,$85,$80,$56,$85,$00,$85
	.byte $52,$85,$82,$22,$85,$80,$56,$85,$00,$89
@ref2:
	.byte $83,$82,$30,$85,$80,$60,$85,$00,$8d,$82,$40,$85,$80,$48,$85,$00
	.byte $8d,$82,$30,$8d,$00,$8d,$22
@ref3:
	.byte $85,$80,$52,$85,$00,$8d,$82,$30,$8d,$00,$8d,$40,$85,$80,$58,$85
	.byte $00,$8d,$82,$30,$85
@ref4:
	.byte $80,$56,$85,$00,$85,$52,$85,$82,$22,$85,$80,$50,$85,$00,$8d,$82
	.byte $30,$8d,$00,$8d,$40,$85,$80,$48,$83
@ref5:
	.byte $00,$8d,$82,$30,$8d,$00,$8d,$22,$85,$80,$52,$85,$00,$8d,$82,$30
	.byte $8d,$00,$83
	.byte $ff,$15
	.word @ref1
@ref7:
	.byte $83,$82,$30,$85,$80,$60,$85,$00,$8d,$82,$40,$85,$80,$48,$85,$00
	.byte $8d,$82,$30,$85,$80,$48,$85,$00,$8d,$82,$22
@ref8:
	.byte $85,$80,$48,$85,$00,$85,$4c,$85,$82,$30,$85,$80,$50,$85,$00,$85
	.byte $52,$85,$82,$40,$85,$80,$58,$85,$00,$8d,$82,$30,$85
@ref9:
	.byte $80,$52,$85,$00,$8d,$82,$22,$85,$80,$56,$85,$00,$8d,$82,$30,$8d
	.byte $00,$8d,$40,$8b
@ref10:
	.byte $00,$8d,$30,$8d,$00,$8d,$22,$85,$80,$52,$85,$00,$8d,$82,$30,$8d
	.byte $00,$83
	.byte $ff,$15
	.word @ref1
	.byte $ff,$12
	.word @ref2
	.byte $ff,$11
	.word @ref3
	.byte $ff,$14
	.word @ref4
	.byte $ff,$10
	.word @ref5
	.byte $ff,$15
	.word @ref1
	.byte $ff,$14
	.word @ref7
@ref18:
	.byte $85,$80,$48,$85,$00,$85,$4c,$85,$00,$85,$50,$85,$00,$85,$52,$85
	.byte $82,$40,$85,$80,$58,$85,$00,$8d,$82,$30,$85
@ref19:
	.byte $80,$56,$85,$00,$8d,$82,$22,$85,$80,$52,$85,$00,$8d,$82,$30,$8d
	.byte $00,$8d,$40,$8b
@ref20:
	.byte $00,$8d,$30,$8d,$00,$8d,$48,$85,$80,$60,$85,$00,$8d,$82,$3a,$85
	.byte $80,$60,$85,$00,$83
@ref21:
	.byte $89,$82,$48,$85,$80,$60,$85,$00,$8d,$82,$3a,$85,$80,$60,$85,$00
	.byte $8d,$82,$48,$85,$80,$62,$85,$00,$85,$60,$81
@ref22:
	.byte $83,$82,$3a,$85,$80,$60,$85,$00,$85,$5c,$85,$82,$48,$85,$80,$5c
	.byte $85,$00,$8d,$82,$3a,$8d,$00,$8d,$44
@ref23:
	.byte $85,$80,$5c,$85,$00,$8d,$82,$36,$85,$80,$5c,$85,$00,$8d,$82,$44
	.byte $85,$80,$5c,$85,$00,$8d,$82,$36,$85
@ref24:
	.byte $80,$5c,$85,$00,$85,$52,$85,$82,$44,$85,$80,$60,$85,$00,$85,$5c
	.byte $85,$82,$36,$85,$80,$5c,$85,$00,$85,$58,$85,$82,$44,$85,$80,$58
	.byte $83
@ref25:
	.byte $00,$8d,$82,$36,$8d,$00,$8d,$40,$85,$80,$58,$85,$00,$8d,$82,$32
	.byte $85,$80,$58,$85,$00,$83
@ref26:
	.byte $89,$82,$40,$85,$80,$58,$85,$00,$8d,$82,$32,$85,$80,$56,$85,$00
	.byte $85,$52,$85,$82,$40,$85,$80,$5c,$85,$00,$89
@ref27:
	.byte $83,$82,$32,$85,$80,$52,$85,$00,$8d,$82,$40,$85,$80,$5c,$85,$00
	.byte $8d,$82,$32,$8d,$00,$8d,$28
@ref28:
	.byte $85,$80,$58,$85,$00,$95,$56,$85,$00,$85,$52,$85,$00,$85,$4e,$85
	.byte $00,$95
@ref29:
	.byte $df,$48,$83
	.byte $fd
	.word @song0ch0loop

@song0ch1:
@song0ch1loop:
@ref30:
	.byte $00,$ad,$80,$52,$8d,$00,$a3
@ref31:
	.byte $89,$58,$8d,$00,$8d,$56,$8d,$52,$8d,$56,$8d,$00,$89
@ref32:
	.byte $83,$60,$8d,$00,$8d,$48,$8d,$00,$ad,$52
@ref33:
	.byte $8d,$00,$ad,$58,$8d,$00,$8d,$56,$85
@ref34:
	.byte $87,$52,$8d,$50,$8d,$00,$ad,$48,$8b
@ref35:
	.byte $00,$ad,$52,$8d,$00,$a3
	.byte $ff,$0d
	.word @ref31
@ref37:
	.byte $83,$60,$8d,$00,$8d,$48,$8d,$00,$8d,$48,$8d,$00,$8d,$48
@ref38:
	.byte $8d,$4c,$8d,$50,$8d,$52,$8d,$58,$8d,$00,$8d,$52,$85
@ref39:
	.byte $87,$00,$8d,$56,$8d,$00,$bb
	.byte $ff,$06
	.word @ref35
	.byte $ff,$0d
	.word @ref31
	.byte $ff,$0a
	.word @ref32
	.byte $ff,$09
	.word @ref33
	.byte $ff,$09
	.word @ref34
	.byte $ff,$06
	.word @ref35
	.byte $ff,$0d
	.word @ref31
	.byte $ff,$0e
	.word @ref37
@ref48:
	.byte $8d,$4c,$8d,$50,$8d,$52,$8d,$58,$8d,$00,$8d,$56,$85
@ref49:
	.byte $87,$00,$8d,$52,$8d,$00,$bb
@ref50:
	.byte $af,$60,$8d,$00,$8d,$60,$8d,$00,$83
@ref51:
	.byte $89,$60,$8d,$00,$8d,$60,$8d,$00,$8d,$62,$8d,$60,$89
@ref52:
	.byte $83,$60,$8d,$5c,$8d,$5c,$8d,$00,$ad,$5c
@ref53:
	.byte $8d,$00,$8d,$5c,$8d,$00,$8d,$5c,$8d,$00,$8d,$5c,$85
@ref54:
	.byte $87,$52,$8d,$60,$8d,$5c,$8d,$5c,$8d,$58,$8d,$58,$8b
@ref55:
	.byte $00,$ad,$58,$8d,$00,$8d,$58,$8d,$00,$83
@ref56:
	.byte $89,$58,$8d,$00,$8d,$56,$8d,$52,$8d,$5c,$8d,$00,$89
@ref57:
	.byte $83,$52,$8d,$00,$8d,$5c,$8d,$00,$ad,$58
@ref58:
	.byte $8d,$00,$8d,$56,$8d,$52,$8d,$4e,$8d,$00,$95
@ref59:
	.byte $d7,$48,$8b
	.byte $fd
	.word @song0ch1loop

@song0ch2:
@song0ch2loop:
@ref60:
	.byte $00,$ad,$84,$0a,$8d,$00,$8d,$18,$8d,$00,$83
@ref61:
	.byte $89,$28,$8d,$00,$8d,$18,$8d,$00,$8d,$0a,$8d,$00,$89
@ref62:
	.byte $83,$18,$8d,$00,$8d,$28,$8d,$00,$8d,$18,$8d,$00,$8d,$0a
@ref63:
	.byte $8d,$00,$8d,$18,$8d,$00,$8d,$28,$8d,$00,$8d,$18,$85
@ref64:
	.byte $87,$00,$8d,$0a,$8d,$00,$8d,$18,$8d,$00,$8d,$28,$8b
@ref65:
	.byte $00,$8d,$18,$8d,$00,$8d,$0a,$8d,$00,$8d,$18,$8d,$00,$83
	.byte $ff,$0d
	.word @ref61
	.byte $ff,$0e
	.word @ref62
	.byte $ff,$0d
	.word @ref63
	.byte $ff,$0d
	.word @ref64
	.byte $ff,$0e
	.word @ref65
	.byte $ff,$0d
	.word @ref61
	.byte $ff,$0e
	.word @ref62
	.byte $ff,$0d
	.word @ref63
	.byte $ff,$0d
	.word @ref64
	.byte $ff,$0e
	.word @ref65
	.byte $ff,$0d
	.word @ref61
	.byte $ff,$0e
	.word @ref62
@ref78:
	.byte $8d,$00,$8d,$00,$8d,$00,$8d,$28,$8d,$00,$8d,$18,$85
	.byte $ff,$0d
	.word @ref64
@ref80:
	.byte $00,$8d,$18,$8d,$00,$8d,$30,$8d,$00,$8d,$22,$8d,$00,$83
@ref81:
	.byte $89,$30,$8d,$00,$8d,$22,$8d,$00,$8d,$30,$8d,$00,$89
@ref82:
	.byte $83,$22,$8d,$00,$8d,$30,$8d,$00,$8d,$22,$8d,$00,$8d,$2c
@ref83:
	.byte $8d,$00,$8d,$1e,$8d,$00,$8d,$2c,$8d,$00,$8d,$1e,$85
@ref84:
	.byte $87,$00,$8d,$2c,$8d,$00,$8d,$1e,$8d,$00,$8d,$2c,$8b
@ref85:
	.byte $00,$8d,$1e,$8d,$00,$8d,$28,$8d,$00,$8d,$1a,$8d,$00,$83
@ref86:
	.byte $89,$28,$8d,$00,$8d,$1a,$8d,$00,$8d,$28,$8d,$00,$89
@ref87:
	.byte $83,$1a,$8d,$00,$8d,$28,$8d,$00,$8d,$1a,$8d,$00,$8d,$10
@ref88:
	.byte $8d,$00,$d5
@ref89:
	.byte $e5
	.byte $fd
	.word @song0ch2loop

@song0ch3:
@song0ch3loop:
@ref90:
	.byte $e5
@ref91:
	.byte $e5
@ref92:
	.byte $e5
@ref93:
	.byte $e5
@ref94:
	.byte $e5
@ref95:
	.byte $e5
@ref96:
	.byte $e5
@ref97:
	.byte $e5
@ref98:
	.byte $e5
@ref99:
	.byte $e5
@ref100:
	.byte $e5
@ref101:
	.byte $e5
@ref102:
	.byte $e5
@ref103:
	.byte $e5
@ref104:
	.byte $e5
@ref105:
	.byte $e5
@ref106:
	.byte $e5
@ref107:
	.byte $e5
@ref108:
	.byte $e5
@ref109:
	.byte $e5
@ref110:
	.byte $e5
@ref111:
	.byte $e5
@ref112:
	.byte $e5
@ref113:
	.byte $e5
@ref114:
	.byte $e5
@ref115:
	.byte $e5
@ref116:
	.byte $e5
@ref117:
	.byte $e5
@ref118:
	.byte $e5
@ref119:
	.byte $e5
	.byte $fd
	.word @song0ch3loop

@song0ch4:
@song0ch4loop:
@ref120:
	.byte $e5
@ref121:
	.byte $e5
@ref122:
	.byte $e5
@ref123:
	.byte $e5
@ref124:
	.byte $e5
@ref125:
	.byte $e5
@ref126:
	.byte $e5
@ref127:
	.byte $e5
@ref128:
	.byte $e5
@ref129:
	.byte $e5
@ref130:
	.byte $e5
@ref131:
	.byte $e5
@ref132:
	.byte $e5
@ref133:
	.byte $e5
@ref134:
	.byte $e5
@ref135:
	.byte $e5
@ref136:
	.byte $e5
@ref137:
	.byte $e5
@ref138:
	.byte $e5
@ref139:
	.byte $e5
@ref140:
	.byte $e5
@ref141:
	.byte $e5
@ref142:
	.byte $e5
@ref143:
	.byte $e5
@ref144:
	.byte $e5
@ref145:
	.byte $e5
@ref146:
	.byte $e5
@ref147:
	.byte $e5
@ref148:
	.byte $e5
@ref149:
	.byte $e5
	.byte $fd
	.word @song0ch4loop